export const siteConfig = {
  name: "Ketul Patel",
  title: "Senior Software Engineer",
  description:
    "Portfolio website of Ketul Patel - Full Stack Developer with 4+ years of experience in Software development, Cloud Computing, and DevOps",
  accentColor: "#4285f4",
  social: {
    email: "ketulpatel3012@gmail.com",
    linkedin: "https://www.linkedin.com/in/ketul-patel-773b4b12b/",
    twitter: "",
    github: "https://github.com/Ketul3012",
  },
  aboutMe:
    "4+ years of experience in Software development, Cloud Computing, and DevOps. Proven ability to quickly learn and apply new technologies and programming languages. Currently pursuing Master of Applied Computer Science at Dalhousie University with expertise in microservices architecture, cloud deployments, and modern web technologies.",
  skills: [
    "Java",
    "Python",
    "JavaScript",
    "TypeScript",
    "React",
    "Node.js",
    "Spring Boot",
    "AWS",
    "Docker",
    "Terraform",
    "Angular",
    "Flutter",
    "PostgreSQL",
    "MySQL",
    "MongoDB",
    "Git",
    "CI/CD",
  ],
  projects: [
    {
      name: "Thermal IP Vision Camera Streaming App",
      bullets: [
        "Cross-platform mobile application built with Flutter for real-time thermal camera streaming and monitoring",
        "Features advanced image processing and live video streaming capabilities with intuitive user interface",
        "Integrated with IP camera protocols for seamless connectivity and optimized for both Android and iOS platforms",
        "Implemented thermal data visualization with real-time processing and monitoring capabilities",
      ],
      link: "https://www.fyrlyt.com/about-us",
      skills: [
        "Flutter",
        "Dart",
        "Mobile Development",
        "Image Processing",
        "Real-time Streaming",
      ],
    },
    {
      name: "Fire Safety Management System",
      bullets: [
        "Comprehensive fire safety management platform built with Next.js and SST (Serverless Stack) architecture",
        "Features real-time monitoring, alert systems, and compliance tracking for emergency response management",
        "Implemented serverless backend with AWS Lambda functions and automated deployment pipelines",
        "Built scalable cloud infrastructure with real-time data processing and notification systems",
      ],
      link: "https://www.certifire.com.au/",
      skills: [
        "Next.js",
        "SST",
        "Serverless",
        "AWS Lambda",
        "Real-time Monitoring",
        "Cloud Architecture",
      ],
    },
    {
      name: "Ticket Management Software",
      bullets: [
        "Full-stack event ticketing platform with Java Spring Boot backend and React frontend",
        "Features dynamic pricing, payment processing with Stripe integration and digital wallet support",
        "Integrated Google/Apple Wallet for seamless digital ticket delivery and event access",
        "Implemented microservices architecture with automated CI/CD pipelines and zero-downtime deployments",
        "Built comprehensive event management system with real-time analytics and reporting",
      ],
      link: "https://www.eventliveus.com/",
      skills: [
        "Java",
        "Spring Boot",
        "React",
        "Stripe",
        "Microservices",
        "CI/CD",
        "AWS",
      ],
    },
    {
      name: "Fish Tracking System",
      bullets: [
        "Real-time aquaculture monitoring and fish tracking system built with React frontend and GoLang backend",
        "Features advanced data analytics, real-time tracking capabilities, and comprehensive reporting dashboards",
        "Integrated with IoT sensors for environmental monitoring and automated data processing",
        "Built scalable aquaculture management system with predictive analytics and alert mechanisms",
      ],
      link: "https://www.innovasea.com/hydroai-fish-counting-system/",
      skills: [
        "React",
        "GoLang",
        "Real-time Analytics",
        "IoT Integration",
        "Data Visualization",
        "Aquaculture Tech",
      ],
    },
    {
      name: "Mortgage Underwriting System",
      bullets: [
        "Enterprise-level mortgage underwriting platform built with Java Spring Boot and Angular frontend",
        "Features automated risk assessment, document processing, and compliance checking with comprehensive reporting",
        "Implemented robust security measures, multi-environment deployment, and integration with financial data sources",
        "Built scalable system for accurate underwriting decisions with real-time risk evaluation and document management",
      ],
      link: "https://www.tcs.com/what-we-do/industries/banking/solution/tcs-digital-mortgage-suite",
      skills: [
        "Java",
        "Spring Boot",
        "Angular",
        "Enterprise Architecture",
        "Financial Systems",
        "Risk Assessment",
      ],
    },
    {
      name: "LearnPro",
      bullets: [
        "AI-powered learning journey platform using ReactJS and LLM integration for personalized education",
        "Features personalized learning paths, progress tracking, and interactive content delivery",
        "Deployed on AWS with Lambda functions and EC2 instances for scalable educational experiences",
        "Implemented automated resource allocation through CloudFormation templates and user-centric learning visualization",
      ],
      link: "https://github.com/Ketul3012/learn-pro/",
      skills: [
        "React",
        "TypeScript",
        "Java",
        "Spring Boot",
        "AWS",
        "LLM Integration",
      ],
    },
    {
      name: "ParkFlex",
      bullets: [
        "Smart parking management system with efficient state management using Zustand and modern styling with TailwindCSS",
        "Features real-time parking availability, payment processing, and comprehensive user management",
        "Deployed with CI/CD pipelines on Netlify and Render for seamless frontend and backend deployment",
        "Utilized MongoDB Atlas for scalable data management and AWS cloud services for optimal performance",
      ],
      link: "https://park-flex.netlify.app/",
      skills: [
        "React",
        "TypeScript",
        "ExpressJS",
        "TailwindCSS",
        "MongoDB",
        "AWS",
        "Zustand",
      ],
    },
  ],
  experience: [
    {
      company: "Eventliveus",
      title: "Senior Software Engineer (Full-Time)",
      dateRange: "Jan 2025 - Present",
      bullets: [
        "Designed and implemented scalable microservices with Spring Boot REST APIs for ticket purchasing, improving system reliability by 40%",
        "Developed dynamic payment installment plans with Stripe integration, increasing ticket sales by 25%",
        "Integrated digital tickets with Google Wallet and Apple Wallet for seamless event access",
        "Enhanced React.js front-end improving user retention by 100% through modern UI components",
        "Automated infrastructure provisioning using Terraform and Pulumi, reducing setup time by 70%",
        "Built GitHub CI/CD pipelines for AWS ECS deployments enabling zero-downtime releases",
      ],
    },
    {
      company: "InnovaSea",
      title: "Full Stack Developer Intern",
      dateRange: "Aug 2024 - Dec 2024",
      bullets: [
        "Developed backend services in GoLang for real-time aquaculture data processing",
        "Built responsive React.js components improving UI performance and user experience",
        "Automated cloud infrastructure provisioning using Terraform and Ansible reducing setup time by 60%",
      ],
    },
    {
      company: "Eventliveus",
      title: "Full Stack Developer (Casual)",
      dateRange: "Aug 2023 - Apr 2024",
      bullets: [
        "Implemented microservices back-end using Spring Boot REST APIs providing 40% performance increase",
        "Utilized React.js to implement attractive front-end increasing user retention by 100%",
        "Crafted GitHub CI/CD pipeline for AWS ECS deployment resulting in 100% uptime",
        "Integrated authentication using Spring Security and OAuth2.0 on AWS Cognito reducing security risks by 90%",
      ],
    },
    {
      company: "Edgetech Studio",
      title: "Software Developer (Part-Time)",
      dateRange: "Jan 2023 - Sep 2023",
      bullets: [
        "Constructed Flutter application for IP thermal camera reducing development costs by 40%",
        "Updated company-marketing website in Angular with animations resulting in 2x more business",
        "Collaborated on fire-safety management application using Serverless architecture with SST and Node.js",
      ],
    },

    {
      company: "Tata Consultancy Services",
      title: "Systems Engineer (Full-Time)",
      dateRange: "Sep 2020 - Jun 2023",
      bullets: [
        "Designed Spring Boot back-end architecture for US mortgage systems enabling faster integration",
        "Led team of developers in learning modern technologies and infrastructures",
        "Executed SQL functions to automate reporting reducing manual effort by 50%",
        "Incorporated Agile methodology using Azure DevOps for effective task tracking",
      ],
    },
  ],
  education: [
    {
      school: "Dalhousie University",
      degree: "Master of Applied Computer Science",
      dateRange: "Sep 2023 - Present",
      achievements: [
        "GPA: 4.25/4.3",
        "Relevant courses: Advanced Cloud Computing Concepts, Advanced Web Development Concepts",
        "Currently pursuing advanced studies in computer science",
      ],
    },
    {
      school: "L.D College of Engineering",
      degree: "Bachelor of Information Technology",
      dateRange: "Aug 2016 - Aug 2020",
      achievements: [
        "GPA: 3.9/4.3",
        "Relevant courses: Software Design Concepts, Advanced Java Concepts",
        "Strong foundation in information technology and software development",
      ],
    },
  ],
};
